version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cloud.google.com/go/pubsub
    versions:
    - 1.10.0
    - 1.10.1
    - 1.10.2
    - 1.9.1
  - dependency-name: google.golang.org/api
    versions:
    - 0.37.0
    - 0.38.0
    - 0.39.0
    - 0.40.0
    - 0.41.0
    - 0.42.0
    - 0.43.0
    - 0.44.0
  - dependency-name: github.com/line/line-bot-sdk-go
    versions:
    - 7.7.0+incompatible
